gameconfig:
  gametime: 300
  autorule: false
  startlocation:
    red:
      x: 0
      y: 0
      z: 0
    blue:
      x: 0
      y: 0
      z: 0
    spawn:
      x: 0
      y: 0
      z: 0



ruleconfig:
  entitykillpenalty: true
  desartdamagerule: true
  magmadeathtopoint: true
  tamereward: true

