name: ConditionPoint
main: sitoa.minecraft.plugin.ConditionPoint.ConditionPoint
version: 0.0.1

commands:
  setteam:
    description: this is set player to team command.
    usages: /setteam <player> <red/blue>
    permission: sitoa.minecraft.plugin.ConditionPoint.setteam
    permission-message: you don't have permission
  gamestart:
     description: gamestart command.
     usages: /gamestart
     permission: sitoa.minecraft.plugin.ConditionPoint.gamestart
     permission-message: you don't have permission
  gamereset:
    description: reset command.
    usages: /gamereset
    permission: sitoa.minecraft.plugin.ConditionPoint.reset
    permission-message: you don't have permission
  startpoint:
    description: set start location command.
    usages: /startpoint [red/blue]
    permission: sitoa.minecraft.plugin.ConditionPoint.setstartpoint
    permission-message: you don't have permission
  setgametime:
    description: set game time command.
    usages: /setgametime [second]
    permission: sitoa.minecraft.plugin.ConditionPoint.setgametime
    permission-message: you don't have permission